### ISSUE TITLE
add context cancelation

### ISSUE THREAD

**Issue by pjebs** [cnkei/gospline#4]
Some of these algorithms take a long time to calculate for massive amounts of data. It would be nice if you implemented context cancelation.

**Comment by rvql** [comment]
Could you please elaborate?
I'm not sure how context cancelation should be integrated into this lib, some example or a pull request would be nice.

**Comment by pjebs** [comment]
For each function that potentially takes a long time to return, add `ctx context.Context` as the first argument.

Then inside the function, check for `if err := ctx.Err(); err != nil { return err } `

**Comment by pjebs** [comment]
?
